import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/top_navbar";
import MiddleNavbar from "@/components/middle_navbar";
import LastNavbar from "@/components/last_navvbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          <MiddleNavbar />
          <LastNavbar />
        </div>
        {children}

        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
